### ISSUE TITLE
Empty branches under stn/src/dynamic_timeout.cc

### ISSUE THREAD

**Issue by spacewander** [Tencent/mars#45]
First of all, thanks for your sharing of WeChat's battlefield-tested network library.

I am just starting reading the code, and find some strange empty branches under
https://github.com/Tencent/mars/blob/master/mars/stn/src/dynamic_timeout.cc

Then I do some search, and find more empty branches in the repo.(via `ag -C 1 '{\s+}$'`).
Maybe some of them could be deleted  safely?

**Comment by garryyan** [comment]
fixed 25554298c7567ccbec2d2bd1a9934d4f3b370a51

empty branches in dynamic_timeout.cc were used to collect statistics data, those could be deleted.

but some eg：
```
if (..) {
...
} else if (...) {
..
} else {

}
```
the "else" branch is empty  just in order to correspond "else if".

and some eg:
```
WEAK_FUNC void foo() {
}
```
can not delete.  These are weak symbol that can be overwrited by function with the same name.


Thanks for your suggestion.
